power: supply: bq25890_charger: Fix unused result warning
../drivers/power/supply/bq25890_charger.c:1100:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
 1100 |                         PTR_ERR(bq->usb);
      |                         ^~~~~~~ ~~~~~~~
../drivers/power/supply/bq25890_charger.c:1107:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
 1107 |                         PTR_ERR(bq->charger);
      |                         ^~~~~~~ ~~~~~~~~~~~
  CC      drivers/power/supply/ln8000_charger.o
../drivers/power/supply/bq25890_charger.c:1595:5: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
 1595 |                                 PTR_ERR(bq->charger);
      |                                 ^~~~~~~ ~~~~~~~~~~~
../drivers/power/supply/bq25890_charger.c:2735:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
 2735 |                         PTR_ERR(bq->charger);
      |                         ^~~~~~~ ~~~~~~~~~~~